### ISSUE TITLE
【认领翻译】JavaScript API

### ISSUE THREAD

**Issue by unbug** [int64ago/wasm-cn#1]
**Web URL**: [https://wasm-cn.org/docs/js/](https://wasm-cn.org/docs/js/)

**File Path**: design/JS.md

**Branch**: master --> [JavaScript_API](https://github.com/unbug/wasm-cn/tree/JavaScript_API)

**Estimated**: 1 Week.

**Status**: In progress.

**Comment by int64ago** [comment]
感谢！

翻译直接从 master 开分支即可，gh-pages 是 CI 自动构建生成的

文件路径：design/JS.md

**Comment by unbug** [comment]
好，我建了个翻译交流 QQ 群（616277321）以备不时之需，欢迎加入 :)

**Comment by int64ago** [comment]
你好，为了防止重复劳动，不介意的话可以到这个仓库参与翻译：https://github.com/WebAssembly-cn/website
